---
label: Blog Section Template
hide_body: false
fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: topTitle
    label: title
  - type: textarea
    name: title
    label: Title
  - type: text
    name: buttonName
    label: Button name
  - type: text
    name: buttonTarget
    label: Button target
pages:
  - data/blogSection.yml
