# In the Name of God, the Originator the Creative
---
label: Config Template
hide_body: true
fields:
  - type: field_group
    name: main
    label: Main menu
    fields:
      - type: field_group_list
        name: main
        label: main
        fields:
          - type: text
            name: name
            label: name
          - type: text
            name: url
            label: url
          - type: number
            name: weight
            label: weight
  - type: field_group_list
    name: sitemap
    label: Sitemap
    fields:
      - type: text
        name: name
        label: name
      - type: text
        name: url
        label: url
      - type: number
        name: weight
        label: weight
pages:
  - config/_default/params.yaml
