# In the Name of God, the Originator the Creative
---
label: Product Section Template
hide_body: false
fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: topTitle
    label: title
  - type: textarea
    name: title
    label: Title
pages:
  - data/productSection.yml
