# In the Name of God, the Originator the Creative
---
label: Product Template
hide_body: false
fields:
  - type: text
    name: title
    label: Title
  - type: datetime
    name: date
    label: date
  - type: file
    name: thumbnail
    label: Thumbnail
  - type: field_group_list
    name: table
    label: Table
    fields:
      - type: text
        name: title
        label: Title
      - type: text
        name: description
        label: Description
  - type: text
    name: categories
    label: Categories
  - type: textarea
    name: shortDescription
    label: shortDescription
pages:
  - content/product/
